version: "3"

services:
  site:
    image: python:3.8-alpine
    entrypoint: /app/scripts/run.sh
    ports:
      - "5000:5000"
    volumes:
    - .:/app
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'dummy_db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./data/dump_apps.sql:/docker-entrypoint-initdb.d/1_dump_apps.sql
      - ./data/dump_customers.sql:/docker-entrypoint-initdb.d/2_dump_customers.sql
      - ./data/dump_users.sql:/docker-entrypoint-initdb.d/3_dump_users.sql
      - ./data/dump_payment_methods.sql:/docker-entrypoint-initdb.d/4_dump_payment_methods.sql
    expose:
      - "3306"
